### ISSUE TITLE
After killed app does not receive notifications

### ISSUE THREAD

**Issue by NikolaStamenov** [CrossGeeks/FirebasePushNotificationPlugin#142]
If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information
After killed app does not receive notifications until next restart.

Version Number of Plugin: 2.1.3
Device Tested On: Huawei X2, P8
Simulator Tested On:
Version of VS: 2017
Version of Xamarin: 4.7.10.38
Versions of other things you are using:

### Steps to reproduce the Behavior
Start the app, then kill it from the tasks, and send a notification to it.

### Expected Behavior
App to receive the push.

### Actual Behavior
App is not receiving the push.

### Screenshots

- It's PCL Android Native app.

**Comment by rubenmv** [comment]
It is working for me, but you need to allow the app in the Protected apps list in your phone's Settings. After that I can kill the app from the task manager and it keeps getting notifications. I think the problem is that Emui kills everything in background if you don't protect the app, pretty annoying.

Works on a Huawei LYO-L21 with Emui 3.1 (Android 5.1). I don't know about newer models.
