### ISSUE TITLE
Sending notification to a specific device IF device is subscribed to a topic

### ISSUE THREAD

**Issue by stavroaudi** [CrossGeeks/FirebasePushNotificationPlugin#172]
I have notification settings where the user can allow and block specific notification types. So I made topics A, B, C for example. If the user allows notifications of type A, then the device will subscribe to topic A. I want to send a unique notification to that device if it is subscribed to notifications of type A. However, it seems that I cannot add two parameters to 'to: '

Currently I have: 

{
  "to": "{device_token}",
  "data": {
    "message": "hello",
   },
   "priority": "high"
}

I tried to add 'condition:  'A' in topics' but it doesn't allow me to have both 'to' and 'condition'.

**Comment by raymondjstone** [comment]
Not sure why you would want to send a unique notification to something subscribed to a topic but worth looking at the firebase server API. Personally I only send to topics and don't sent directly to devices. But since you have the device token you can get a list of all topics that it is subscribed to and then generate your unique message as required.
