### ISSUE TITLE
Heads up notification not displaying

### ISSUE THREAD

**Issue by rgwebb** [CrossGeeks/FirebasePushNotificationPlugin#215]
## Bug Information

I am passing a notification with priority: high parameter but the heads up notification window will not display.

Version Number of Plugin: 2.3.5
Device Tested On: Samsung Galaxy S9+
Simulator Tested On: N/A
Version of VS: VS 2017 15.9.6
Version of Xamarin: 28.0.0
Versions of other things you are using: XamForms 3.4.0.1009999

### Steps to reproduce the Behavior

Receive notification with high priority

### Expected Behavior

Heads up notification displayed

### Actual Behavior
Notification is sent to the background instead of displaying the heads-up UI

**Comment by weases** [comment]
Have you checked [this](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/issues/183)?

**Comment by dercdev** [comment]
Hello,

i am running on a Samsung Active Tab 2 and also get NO head-up UI

**Comment by mimunoz** [comment]
Hi, that happens because [here](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/src/Plugin.FirebasePushNotification.Android/FirebasePushNotificationManager.cs#L224) in the plugin initialization the channel importance is setted with "Default" value. I cloned repo to test and change this value to "HIGH" and heads up appearing. I made PR with this little change but @rdelrosario say nothing yet. 

Regards.

**Comment by rdelrosario** [comment]
This is now supported on latest version you can set the importance for the default notification channel.

**Comment by rdelrosario** [comment]
```cs
FirebasePushNotificationManager.DefaultNotificationChannelImportance = NotificationImportance.High;
```
Before initializing the plugin

**Comment by DeanZhuo** [comment]
Still having this issue. Message received with no notification display. Please help
