### ISSUE TITLE
Device token getting generated in strange format - Xamarin.iOS

### ISSUE THREAD

**Issue by arvindrajachourasiya** [CrossGeeks/FirebasePushNotificationPlugin#229]
Please visit this stackoverflow question

https://stackoverflow.com/questions/55594820/device-token-getting-generated-in-strange-format-xamarin-ios

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

**Comment by fullyBoricua** [comment]
I had a similar error a while back... it was a FCM registration issue related to having multiple projects inside the `google-services.json` file.

I know this is a longshot, but worth a try since it will only take 2 minutes:

1. remove any other apps from the FB console if possible (or create a new FB project if not)
2. delete google-services.json file from your project
3. make sure there isn't a copy of the file inside the Resources folder in the Android / iOS projects
4. clean solution
5. download google-services.json again from the FB console and add it to the project
