### ISSUE TITLE
Error The "LinkAssemblies" task failed unexpectedly. Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.FirebasePushNotification.FirebasePushNotificationManager:

### ISSUE THREAD

**Issue by jadson-medeiros** [CrossGeeks/FirebasePushNotificationPlugin#252]
Hello guys, Someone can help with this problem??

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Void Plugin.FirebasePushNotification.FirebasePushNotificationManager::Subscribe(System.String)' in assembly: 'Plugin.FirebasePushNotification.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void Firebase.Messaging.FirebaseMessaging::SubscribeToTopic(System.String)
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	MyStoreApp02.Droid

**Comment by ricardoprestes** [comment]
The same problem with me

**Comment by jadson-medeiros** [comment]
You need to update the other packages

**Comment by JFMG** [comment]
@jadson-medeiros which packages do you mean? All my packages are up to date.

**Comment by valentin-debris** [comment]
@JFMG all the android packages Xamarin.Firebase.* have to be set to the same version. 
Actually, you should use the v60.1142.1 if you use this plugin, newest stable versions are not working.
![image](https://user-images.githubusercontent.com/5438977/63851316-5b90bb80-c996-11e9-9019-0452b9d9f61c.png)
(no need to have them all, it's just to show you)

**Comment by JFMG** [comment]
Here's what I tried so far to fix the problem:
1. Analysing the error message it looks like  'System.Void Plugin.FirebasePushNotification.FirebasePushNotificationManager::Subscribe(System.String)'  is stripped out. **Setting the Linker options in the Android project to None is fixing the problem** for now. But this is not a good solution when you want to release the app because the APK file size is increasing a lot when you switch the Linker options to None.
2. With Linker options set to Link SDK assemblies only, I added Plugin.FirebasePushNotification to the ignored assemblies. Unfortunately without success. It didn't change the problem.
3. With Linker options set to Link SDK assemblies only, I added a LinkDescription.xml file into my Android project with the following content:
```xml
<linker> 
  <assembly fullname="Plugin.FirebasePushNotification">
    <type
      fullname="Plugin.FirebasePushNotification"
      preserve="All" />
  </assembly>
</linker>
```
**unfortunately without success. It didn't change the problem either.**

Any suggestions? Did I make something wrong? Or does the library needs an update?

**Comment by JFMG** [comment]
@valentin-debris Thanks for your answer. Currently I am thinking about switching to App Center. There is a push library which I will test. If everything works we don't need the Plugin.FirebasePushNotification library anymore.

Here are more information about App Center Push:
https://docs.microsoft.com/en-us/appcenter/sdk/push/xamarin-ios

**Comment by valentin-debris** [comment]
@JFMG 
I'm really interesting for your feedback about the appcenter plugin, I will switch to it if it works great :)

**Comment by Nikitkao** [comment]
Hi, you can try to use this one https://www.nuget.org/packages/Birdie.Plugin.FirebasePushNotification/

**Comment by seddik** [comment]
> Hi, you can try to use this one https://www.nuget.org/packages/Birdie.Plugin.FirebasePushNotification/
> @jadson-medeiros

yes birdie plugin solved my issue, it have been updated 28 days ago and suporting the new xamarin.firebase.messaging 7X.XXX version.

**Comment by GO74** [comment]
> 
> 
> Hi, you can try to use this one https://www.nuget.org/packages/Birdie.Plugin.FirebasePushNotification/
> @jadson-medeiros

This smells funny. The Birdie.Plugin.FirebasePushNotification project site is terminating in the same git as Plugin.FirebasePushNotification. Can someone explain what is going on, please?

**Comment by Nikitkao** [comment]
> > Hi, you can try to use this one https://www.nuget.org/packages/Birdie.Plugin.FirebasePushNotification/
> > @jadson-medeiros
> 
> This smells funny. The Birdie.Plugin.FirebasePushNotification project site is terminating in the same git as Plugin.FirebasePushNotification. Can someone explain what is going on, please?

Hi just updated packages

**Comment by rdelrosario** [comment]
Please test this beta and let me know if solves your issues: https://www.nuget.org/packages/Plugin.FirebasePushNotification/3.0.1-beta

**Comment by JFMG** [comment]
@valentin-debris App Center Push works like a charm! I just can recommend to everyone to switch to App Center. It needs some setup but it’s much more comfortable.

**Comment by valentin-debris** [comment]
@JFMG I took a look 1 month ago but App Center Push seems not good for what my needs. I need to be able to subscribe to multiples topics to receive automatics notif depending of what the user do. App Center Push seems good only if you want to send manual push, am I right ?

**Comment by JFMG** [comment]
@valentin-debris There are some manual steps you need to configure to make it work with your requirements but it's possible. The subscription to topics as it is e.g. available on Android is something you need to implement on your own. But then you can listen with App Center Push to the notifications. But the idea is different with App Center. When you register a device for push notifications you will get an ID with App Center which you can provide to your backend. This ID is app center specific but somewhat like the push token you get, if you'd implement push natively. You will then have to use your own topic subscription logic in your own backend because this is something that is not available on every OS. Please remember App Center is an easy to use NuGet to make Push Notifications work fast but if you need something specific, you will have to put more work into it. But theoretically it's the same work you'd do anyway, because iOS has no topics to subscribe to by default. I hope I could help you.

**Comment by juabara** [comment]
The issue still remains for me, are there any solution or workaround to make it work?

**Comment by wawoohdavid7** [comment]
I'm still encountering the same issue, even at the latest version (3.4.35). Same with others it only works when I set it to Don't Link Assemblies. Is there anyone that have some solutions/work-arounds to fix it?
