### ISSUE TITLE
Getting received notification when app closed on IOS

### ISSUE THREAD

**Issue by kerbooo** [CrossGeeks/FirebasePushNotificationPlugin#295]
Hello, is there any method for getting received notification when app closed on IOS.

Below code works on android.
```

CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
{

};
```

**Comment by kerbooo** [comment]
@rdelrosario hello again. Does any way to get?

**Comment by kerbooo** [comment]
Hello again I have created a post on Stackoverflow. I need to know is it possible or not. Pelase give me a advice 

https://stackoverflow.com/questions/60286303/getting-silent-notification-values-when-app-starts

**Comment by mimunoz** [comment]
Hi, are you try creating your own UserNotificationCenterDelegate? When app its terminate this delegate catch the notification and you can manage whatever you want, alert presentation(on/off), tapped action to open a view o do nothing, etc.
```
FirebasePushNotificationManager.Initialize(options, true);
FirebasePushNotificationManager.CurrentNotificationPresentationOption = UNNotificationPresentationOptions.Alert | UNNotificationPresentationOptions.Sound;
UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();
```

[[ref](https://stackoverflow.com/questions/40942988/how-do-i-use-delegates-within-xamarin-specifically-unusernotificationcenterdele)]

**Comment by kerbooo** [comment]
Firstly thank you for your answer @mimunoz . is this work when user terminated app?

**Comment by kerbooo** [comment]
@mimunoz Hello again. I have tried approach in ref. But I did not get any result. I think silent payload can not create a notification on `UNUserNotificationCenter.Current` object 

Because I am getting **alert type notification** which is unopened with `await UNUserNotificationCenter.Current.GetDeliveredNotificationsAsync();` method. I think that is not possible or I did not find correct approach.

**Comment by RobertoGemo** [comment]
@mimunoz  hi.
I have same problem.
What i don't understand is that before the component update all semmed to work.
I have this in the app delegate:
FirebasePushNotificationManager.Initialize(options, new PushNotificationHandler(), true);
UNUserNotificationCenter.Current.GetNotificationSettings((settings) => {
var alertsAllowed = (settings.AlertSetting == UNNotificationSetting.Enabled);

                if (!alertsAllowed)
                {
                    UNUserNotificationCenter.Current.RequestAuthorization(UNAuthorizationOptions.Alert, (approved, err) => {
                        // Watch for notifications while the app is active
                        UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();
                    });
                }
                else
                {
                    UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();
                }

            });

and actually when app i active i regularly receive the notification and can handle it in my custom push notification handler.

but wheh the app is closed the notification is discarded by the system because it has "no user visible content, sound, or badge".
but i didn't change anytghing in the notification structure. i send only content data because i DON'T want that ios handle the notification by itself, i want always handle the notification with my application sound.
it worked... but now  is not... and i don't understand why

**Comment by RobertoGemo** [comment]
this is the log message found on Device:
[com.GruppoInformatico.EasyGAV] Received remote notification request BDEF-0FE4 [ hasAlertContent: 0, hasSound: 0 hasBadge: 0 hasContentAvailable: 1 hasMutableContent: 0 ]

If the app ios opened this is not a problem, and my custom notification handler is "fired"
if the app is closed is not delivered, and it seems that the system cancel the notification without let me handle it.
if i add for example a body to the notification averything works but simply besause the system handle the notification process by itself without let me handle the notification.

thanks

**Comment by AbuMandour** [comment]
any update?
