### ISSUE TITLE
OnTokenRefresh() when app is closed

### ISSUE THREAD

**Issue by rascandelari** [CrossGeeks/FirebasePushNotificationPlugin#296]
Hello, first of all thank you for the plugin, it is working very well and helped me alot in my project. I just have one small issue: I believe my token is refreshing after some weeks but that happens when the app is closed then my app doesn't know that the token has refreshed so it can't pass it to the server resulting in the app stopping to receive notifications. What is the correct way to deal with this issue? 
Im using an Android device with the initialization set false to ResetToken.

Thanks

**Comment by mimunoz** [comment]
Hi, you need to have a service where save the token associated to user(taken from login if you have it), and call it in the OnTokenRefresh. At least this is my way and works. If the token it's refreshed or not don't really care, because the notification it's sent to the user(with associate token).

Regards!
