### ISSUE TITLE
No event on data only firebase message

### ISSUE THREAD

**Issue by christophedemey** [CrossGeeks/FirebasePushNotificationPlugin#33]
Hi

I am trying to send a data message but event is not triggered.
I am using FirebaseNet nuget package as shown in the docs.

When i do :
`    FCMClient client = new FCMClient(serverKey);

            var message = new Message()
            {
                Data = data,
            };

            message.RegistrationIds = registrationIds;

            var result = await client.SendMessageAsync(message);
            DownstreamMessageResponse specificResult = (DownstreamMessageResponse)result;`

No events, and a success response from firebase.

When i add the Notification section i do get the event with the data, but i also get the notification ofcourse.

`    FCMClient client = new FCMClient(serverKey);

            var message = new Message()
            {
                Data = data,
                Notification = new AndroidNotification()
                {
                    Body = body,
                    Title = title,
                }
            };

            message.RegistrationIds = registrationIds;

            var result = await client.SendMessageAsync(message);
            DownstreamMessageResponse specificResult = (DownstreamMessageResponse)result;`

I have attached to the handler in Android

`     //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>
            {

            };`

And the one in App.cs

`    private void Current_OnNotificationReceived(object source, FirebasePushNotificationDataEventArgs e)
        {

        }`

Neither one of them trigger with the data only.
Any idea's ?

Thanks!

**Comment by rdelrosario** [comment]
The problem is you are using notification messages instead of data messages, the only messages handled by client app are the data messages. Here more info: [Receiving notifications](https://github.com/CrossGeeks/FirebasePushNotificationPlugin/blob/master/docs/FirebaseNotifications.md)

**Comment by rdelrosario** [comment]
Remove this from the message:

    Notification = new AndroidNotification()
            {
                Body = body,
                Title = title,
            }

**Comment by christophedemey** [comment]
Hi @rdelrosario 

Thank you for you answer, i guess i was not clear enough in my description.
When i remove the part you are showing i get no events even though the data part is filled in with a dictionary<T,T> which has values.
The firebase service responds with succeeded.

When i add the notification part it does receive, but then i have the notification which i dont need in this scenario.
But this does prove the wiring is all correct.

Thanks.

**Comment by rdelrosario** [comment]
Can you send me the complete payload you are sending without a notification part? 

Did you try one of the samples on the docs?

**Comment by christophedemey** [comment]
Hi @rdelrosario

I now get the event for a data message but also still a notification pop-up, is it normal to always get a notification popup ?

I am using FireBaseNet, the example from this page : https://github.com/tiagomtotti/firebaseNet for data messages, i removed the body key/value so i would not get a notification but i am still getting a notification (empty one).

This is the code i am using : 

`    FCMClient client = new FCMClient(serverKey);

            var message = new Message()
            {
                To = registrationId,
                Data = new Dictionary<string, string>
                {
                    { "Nick", "Mario" },
                    { "Room", "PortugalVSDenmark" }
                }
            };

            var result = await client.SendMessageAsync(message);
            DownstreamMessageResponse specificResult = (DownstreamMessageResponse)result;`

I tried getting the payload it's sending with wireshark but it's encrypted :-(

Thanks.

**Comment by christophedemey** [comment]
This is the effect i have with the code above :

![notification](https://user-images.githubusercontent.com/13153164/31196246-50a79eca-a94d-11e7-8185-94869704434e.PNG)

**Comment by rdelrosario** [comment]
Try this:

 ```cs
Task.Run(async() => {
 
            FCMClient client = new FCMClient("YOUR_APP_SERVER_KEY"); //as derived from https://console.firebase.google.com/project/
            
            
            var message = new Message()
            {
                To = "DEVICE_ID_OR_ANY_PARTICULAR_TOPIC", //topic example /topics/all
                Notification = new AndroidNotification()
                {
                    Body = "Hello World",
                    Title = "MyApp",
                },
                
                Data = new Dictionary<string, string>
                {
                    { "number", "1" },
                    { "count", "10" }
                }
            };
           
            var result = await client.SendMessageAsync(message);
            return result;
 });
```

**Comment by rdelrosario** [comment]
Yes is normal to get the notification, this is the expected behavior. You can control what is displayed on the title and message. Here is all the info:

the plugin uses the default push notification handler to create the notification ui & actions support when sending Data messages.

There are a few things you can configure in Android project using the following static properties from FirebasePushNotificationManager class:
//The sets the key associated with the value will be used to show the title for the notification
public static string NotificationContentTitleKey { get; set; }

//The sets the key associated with the value will be used to show the text for the notification
public static string NotificationContentTextKey { get; set; }

//The sets the resource id for the icon will be used for the notification
public static int IconResource { get; set; }

//The sets the sound  uri will be used for the notification
public static Android.Net.Uri SoundUri { get; set; }
If NotificationContentTitleKey not set will look for title key value to set the title. If no title key present will use the application name as the notification title.

If NotificationContentTextKey not set will look for one of the following keys value in the priority order shown below to set the message for the notification:

alert
body
message
subtitle
text
title
Once one of the above keys is found on the notification data message will shown it's value as the notification message.

id key is set as the notification id if present.
tag key is set as the notification tag if present.
If you send a key called silent with value true it won't display a notification.
For notification with actions will look for click_action key value as the match. More information here: Notification Actions

**Comment by christophedemey** [comment]
HI @rdelrosario 

Yeah, the silent key did the trick : -)
When the app is in background and i send a notification/data combination, is the handler in the android application only processed on notification click ?

Or is it always processed immediately even when the app is in background ?

This handler  : 
`   //Handle notification when app is closed here
            CrossFirebasePushNotification.Current.OnNotificationReceived += (s, p) =>`

**Comment by rdelrosario** [comment]
This handler is just fired when receives the notification immediately if you are using data messages. I will recommend not to use notification message and always send it as data message.

**Comment by christophedemey** [comment]
Hi @rdelrosario 

Thanks again for the help!
